### ISSUE TITLE
Not up-to-date with TF

### ISSUE THREAD

**Issue by stalgiag** [dyelax/Adversarial_Video_Generation#12]
I get the error:
`'module' object has no attribute 'SummaryWriter'`
which I found out is due to a [deprecation in the code](http://stackoverflow.com/questions/41482913/module-object-has-no-attribute-summarywriter). 
I recommend changing these lines or updating the FAQ to suggest a specific version of TensorFlow.

Thanks for your work! Hopefully I can get it up and running.

**Comment by dyelax** [comment]
Hey, yep currently this code only works with TF 0.12. I'll be updating it soon though! Thanks for the heads up

**Comment by stalgiag** [comment]
Thanks for the quick reply! I'll go back to 0.12 in the meantime.
